version: v1.0
name: Deploy new image and restart
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Deploy
    task:
      secrets:
        - name: prod-deploy-details
      jobs:
        - name: Pull image & restart bot
          commands:
            - chmod 400 /home/semaphore/.ssh/id_rsa
            - ssh-keyscan -p ${PROD_SSH_PORT} -H ${PROD_SSH_HOST} >> /home/semaphore/.ssh/known_hosts
            - "ssh ${PROD_SSH_USER}@${PROD_SSH_HOST} -p ${PROD_SSH_PORT} sudo /opt/k3s/merlijn/melijn-backend/deploy.sh ${SEMAPHORE_GIT_SHA}"